env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 7
  sourceType: module
plugins:
  - react
rules: { "react/jsx-filename-extension": [0] }
settings:
  react:
    version: 'latest'
